# Generated by Django 3.1 on 2020-08-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gardeneritem',
            name='created_date',
        ),
        migrations.AddField(
            model_name='gardeneritem',
            name='content',
            field=models.TextField(default='eastern teaberry'),
        ),
        migrations.AlterField(
            model_name='gardeneritem',
            name='name',
            field=models.TextField(default='eastern teaberry', max_length=140),
        ),
    ]
